name: pillu_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  clean_architecture_with_state_management: ^1.1.2

  bloc: ^8.1.4
  flutter_hooks: ^0.21.1-pre.2
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  nb_utils: ^7.0.3

  get_it: ^7.7.0
  mix: ^1.4.0
  provider: ^6.1.2
  equatable: ^2.0.5
  fpdart: ^1.1.0
  go_router: ^14.2.0
  http: ^1.2.1

  # Code generator
  envied: ^0.5.4+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  easy_localization: ^3.0.7
  dartz: ^0.10.1
  flutter_parsed_text: ^2.2.1
  url_launcher: ^6.3.0
  flutter_link_previewer:
    path: lib/flutter_link_previewer-main
  flutter_chat_types:
    path: lib/flutter_chat_types-main
  flutter_chat_ui:
    path: lib/flutter_chat_ui-main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true