name: pillu_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_linkify: ^6.0.0
  html: ^0.15.4
  linkify: ^5.0.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: '>=1.8.0 <2.0.0'
  cloud_firestore: ^5.6.4
  cupertino_icons: ^1.0.8
  faker: ^2.1.0
  file_picker: ^9.0.0
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  firebase_storage: ^12.4.3
  flutter_hooks: ^0.20.5
  flutter:
    sdk: flutter
  diffutil_dart: '>=3.0.0 <5.0.0'
  flutter_parsed_text: ^2.2.1
  intl: '>=0.17.0 <1.0.0'
  photo_view: ^0.15.0
  scroll_to_index: ^3.0.1
  url_launcher: '>=6.1.12 <7.0.0'
  visibility_detector: ^0.4.0+2
  http: '>=0.13.6 <2.0.0'
  image_picker: ^1.1.2
  mime: ^2.0.0
  #  open_filex: ^4.6.0
  path_provider: ^2.1.3
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  google_fonts: ^4.0.4
  cached_network_image: ^3.4.1
  weather_animation: ^1.1.2
  provider: ^6.1.2
  supabase_flutter: ^2.8.3
  firebase_remote_config: ^5.4.1
  open_file: ^3.5.10

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/flutter_chat_ui-main/lib/pillu_assets/
    - lib/flutter_chat_ui-main/lib/pillu_assets/2.0x/
    - lib/flutter_chat_ui-main/lib/pillu_assets/3.0x/
    - lib/flutter_chat_ui-main/lib/pillu_assets/icon-attachment.png
