// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAudzG7V6Ft_80T9IMGpxHk9swbhRDfpA8',
    appId: '1:693866944655:web:4ff672eb312b786c00f8fa',
    messagingSenderId: '693866944655',
    projectId: 'pillu-darling',
    authDomain: 'pillu-darling.firebaseapp.com',
    databaseURL: 'https://pillu-darling-default-rtdb.firebaseio.com',
    storageBucket: 'pillu-darling.firebasestorage.app',
    measurementId: 'G-R0KEZHCH3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIPOWRe8iwu644VFA6otojEx2zCefJ1FM',
    appId: '1:693866944655:android:fc74c6b5e471243900f8fa',
    messagingSenderId: '693866944655',
    projectId: 'pillu-darling',
    databaseURL: 'https://pillu-darling-default-rtdb.firebaseio.com',
    storageBucket: 'pillu-darling.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABSc3RUTKtQK_zCcQPpo6urv-szEM_P8s',
    appId: '1:693866944655:ios:3063f127d64a0ccf00f8fa',
    messagingSenderId: '693866944655',
    projectId: 'pillu-darling',
    databaseURL: 'https://pillu-darling-default-rtdb.firebaseio.com',
    storageBucket: 'pillu-darling.firebasestorage.app',
    androidClientId: '693866944655-6c4dp9s9moc545a8g3958k8vtj351tqr.apps.googleusercontent.com',
    iosClientId: '693866944655-ivn3qd5kq38qj96hmggutqhb3k3cs6u3.apps.googleusercontent.com',
    iosBundleId: 'com.pillu.pilluApp',
  );

}