// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAudzG7V6Ft_80T9IMGpxHk9swbhRDfpA8',
    appId: '1:693866944655:web:7d41b34bf2cee57500f8fa',
    messagingSenderId: '693866944655',
    projectId: 'pillu-darling',
    authDomain: 'pillu-darling.firebaseapp.com',
    databaseURL: 'https://pillu-darling-default-rtdb.firebaseio.com',
    storageBucket: 'pillu-darling.appspot.com',
    measurementId: 'G-99NNM1L9M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIPOWRe8iwu644VFA6otojEx2zCefJ1FM',
    appId: '1:693866944655:android:c0519065b82dc15800f8fa',
    messagingSenderId: '693866944655',
    projectId: 'pillu-darling',
    databaseURL: 'https://pillu-darling-default-rtdb.firebaseio.com',
    storageBucket: 'pillu-darling.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABSc3RUTKtQK_zCcQPpo6urv-szEM_P8s',
    appId: '1:693866944655:ios:e24726111dbdc6d000f8fa',
    messagingSenderId: '693866944655',
    projectId: 'pillu-darling',
    databaseURL: 'https://pillu-darling-default-rtdb.firebaseio.com',
    storageBucket: 'pillu-darling.appspot.com',
    androidClientId: '693866944655-6c4dp9s9moc545a8g3958k8vtj351tqr.apps.googleusercontent.com',
    iosClientId: '693866944655-ivn3qd5kq38qj96hmggutqhb3k3cs6u3.apps.googleusercontent.com',
    iosBundleId: 'com.pillu.pilluApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosClientId: '',
    iosBundleId: '',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    authDomain: '',
    storageBucket: '',
  );
}